### ISSUE TITLE
Trigger redeployment when leaving a specific comment in the PR

### ISSUE THREAD

**Issue by maxyzli** [MurmurationsNetwork/MurmurationsServices#657]
Example to try out

```
name: Deploy on Comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: >-
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'deploy my service') &&
      (github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association == 'MEMBER')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Service
        run: |
          # Add your deployment commands here
          echo "Deploying the service..."

```
